# Generated by Django 6.0 on 2025-12-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("standard", "Стандартный"),
                    ("blocked", "Заблокированный"),
                    ("junior_admin", "Мл. администратор"),
                    ("senior_admin", "Ст. администратор"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
