# Generated by Django 6.0 on 2025-12-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_server", "0002_user_role_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_expired",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
