# Generated by Django 6.0 on 2025-12-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="Non existent", max_length=100),
            preserve_default=False,
        ),
    ]
